spring.application.name=pharmacy-service
server.port=8081

# Import configuration from Spring Cloud Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Actuator
management.endpoints.web.exposure.include=*
