spring.application.name=warehouse-service
server.port=8082

# Import configuration
spring.config.import=optional:configserver:http://localhost:8888

# Actuator
management.endpoints.web.exposure.include=*
