server.port=8888
spring.application.name=config-server

# Git repository configuration
spring.cloud.config.server.git.uri=https://github.com/NamNT2942003/microservice_session9.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.search-paths=config-repo,config,.

# Actuator endpoints
management.endpoints.web.exposure.include=*
